"use strict";
let myName = document.getElementById("name");
console.log("😊 ~ myName:", myName);
let jobTittle = document.getElementById("job");
console.log("😊 ~ jobTittle:", jobTittle);
let myPhone = document.getElementById("phone");
console.log("😊 ~myPhonee:", myPhone);
let myEmail = document.getElementById("email");
console.log("😊 ~ myEmail:", myEmail);
let address = document.getElementById("add");
console.log("😊 ~address:", address);
let passingYear1 = document.getElementById("pass1");
console.log("😊 ~ passingYear1:", passingYear1);
let degree = document.getElementById("deg");
console.log("😊 ~ degree:", degree);
let institute = document.getElementById("uni");
console.log("😊 ~ institute:", institute);
let pass2 = document.getElementById("pass2");
console.log("😊 ~ pass2:", pass2);
let deg2 = document.getElementById("deg2");
console.log("😊 ~ deg2:", deg2);
let uni2 = document.getElementById("uni2");
console.log("😊 ~ uni2:", uni2);
let lang1 = document.getElementById("lang1");
console.log("😊 ~ lang1:", lang1);
let lang2 = document.getElementById("lang2");
console.log("😊 ~ lang2:", lang2);
let lang3 = document.getElementById("lang3");
console.log("😊 ~ lang2:", lang3);
let skill1 = document.getElementById("skill1");
console.log("😊 ~skill1:", skill1);
let skill2 = document.getElementById("skill2");
console.log("😊 ~skill2:", skill2);
let skill3 = document.getElementById("skill3");
console.log("😊 ~skill3:", skill3);
let skill4 = document.getElementById("skill4");
console.log("😊 ~skill4:", skill4);
let job = document.getElementById("jobTitle");
console.log("😊 ~ job:", job);
let year = document.getElementById("year");
console.log("😊 ~year:", year);
let company = document.getElementById("company");
console.log("😊 ~company:", company);
let comppanyLoc = document.getElementById("comlocation");
console.log("😊 ~comppanyLoc:", comppanyLoc);
let achievement1 = document.getElementById("achv1");
console.log("😊 ~achievement1:", achievement1);
let achievement2 = document.getElementById("achv2");
console.log("😊 ~achievement2:", achievement2);
let achievement3 = document.getElementById("achv3");
console.log("😊 ~achievement3:", achievement3);
